services:
  - type: web
    name: chatwoot-web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: RAILS_ENV
        value: production
      - key: INSTALLATION_ENV
        value: docker
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: FRONTEND_URL
        value: https://TU-DOMINIO-RENDER   # <-- cámbialo tras el primer deploy
      - key: FORCE_SSL
        value: "true"
      - key: DEFAULT_LOCALE
        value: es
      - key: ACTIVE_STORAGE_SERVICE
        value: local
      - key: REDIS_URL
        fromService:
          name: chatwoot-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: chatwoot-postgres
          property: connectionString
    startCommand: >
      bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0 -p 10000
    healthCheckPath: /

  - type: worker
    name: chatwoot-sidekiq
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: RAILS_ENV
        value: production
      - key: INSTALLATION_ENV
        value: docker
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      # Usa el MISMO SECRET_KEY_BASE que el web (después lo pegas en el panel)
      - key: SECRET_KEY_BASE
        sync: false
      - key: REDIS_URL
        fromService:
          name: chatwoot-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: chatwoot-postgres
          property: connectionString
    startCommand: >
      bundle exec sidekiq -q critical -q default -q low

  - type: redis
    name: chatwoot-redis
    plan: starter

databases:
  - name: chatwoot-postgres
    databaseName: chatwoot_production
    plan: starter
