services:
  - type: web
    name: chatwoot-web
    env: docker
    dockerfilePath: ./Dockerfile.web   # <- comando en el Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: RAILS_ENV
        value: production
      - key: INSTALLATION_ENV
        value: docker
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: FRONTEND_URL
        value: https://TU-DOMINIO-RENDER        # cámbialo tras el primer deploy por la URL real
      - key: FORCE_SSL
        value: "true"
      - key: DEFAULT_LOCALE
        value: es
      - key: ACTIVE_STORAGE_SERVICE
        value: local
      - key: REDIS_URL
        fromService:
          type: redis
          name: chatwoot-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: chatwoot-postgres
          property: connectionString
    healthCheckPath: /

  - type: worker
    name: chatwoot-sidekiq
    env: docker
    dockerfilePath: ./Dockerfile.sidekiq  # <- comando en el Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: RAILS_ENV
        value: production
      - key: INSTALLATION_ENV
        value: docker
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      # Usa el mismo SECRET_KEY_BASE que el web (pégalo después del primer deploy)
      - key: SECRET_KEY_BASE
        value: ""
      - key: REDIS_URL
        fromService:
          type: redis
          name: chatwoot-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: chatwoot-postgres
          property: connectionString

  - type: redis
    name: chatwoot-redis
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: open for services (ajústalo luego)

databases:
  - name: chatwoot-postgres
    databaseName: chatwoot_production
    plan: starter
